// <auto-generated />
using System;
using MenuMate.Modules.ShoppingLists.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuMate.Modules.ShoppingLists.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ShoppingListsDbContext))]
    partial class ShoppingListsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shopping_lists")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Entities.ShoppingListItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_stock");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_purchased");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("QuantityKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quantity_kind");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_items");

                    b.HasIndex("IsInStock")
                        .HasDatabaseName("ix_shopping_list_items_is_in_stock");

                    b.HasIndex("IsPurchased")
                        .HasDatabaseName("ix_shopping_list_items_is_purchased");

                    b.HasIndex("ShoppingListId", "NormalizedName")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id_normalized_name");

                    b.ToTable("shopping_list_items", "shopping_lists");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Entities.ShoppingListRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("SourceMenuPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_menu_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shopping_lists");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shopping_lists_created_at");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_shopping_lists_owner_user_id");

                    b.HasIndex("SourceMenuPlanId")
                        .HasDatabaseName("ix_shopping_lists_source_menu_plan_id");

                    b.ToTable("shopping_lists", "shopping_lists");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.MenuPlanItemSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MenuPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_plan_id");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.HasKey("Id")
                        .HasName("pk_menu_plan_items");

                    b.HasIndex("MenuPlanId")
                        .HasDatabaseName("ix_menu_plan_items_menu_plan_id");

                    b.ToTable("menu_plan_items", "menu_planning", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.MenuPlanSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_plans");

                    b.ToTable("menu_plans", "menu_planning", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.RecipeIngredientSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("NormalizedProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_product_name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("QuantityKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quantity_kind");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.ToTable("recipe_ingredients", "recipes", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.RecipeSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", "recipes", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Entities.ShoppingListItemRecord", b =>
                {
                    b.HasOne("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Entities.ShoppingListRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_shopping_lists_shopping_list_id");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.MenuPlanItemSourceRecord", b =>
                {
                    b.HasOne("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.MenuPlanSourceRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("MenuPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_plan_items_menu_plans_menu_plan_id");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.RecipeIngredientSourceRecord", b =>
                {
                    b.HasOne("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.RecipeSourceRecord", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Entities.ShoppingListRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.MenuPlanSourceRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MenuMate.Modules.ShoppingLists.Infrastructure.Database.Source.RecipeSourceRecord", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
