// <auto-generated />
using System;
using MenuMate.Modules.RecipeImports.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable
#pragma warning disable CA1716, IDE0161

namespace MenuMate.Modules.RecipeImports.Infrastructure.Database.Migrations
{
    [DbContext(typeof(RecipeImportsDbContext))]
    [Migration("20260613180902_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("imports")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMate.Modules.RecipeImports.Infrastructure.Database.Entities.RecipeImportDraftRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_recipe_id");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RecipeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recipe_json");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_recipe_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recipe_import_drafts");

                    b.HasIndex("CreatedRecipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_import_drafts_created_recipe_id")
                        .HasFilter("created_recipe_id IS NOT NULL");

                    b.HasIndex("TargetRecipeId")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_import_drafts_target_recipe_id");

                    b.HasIndex("OwnerUserId", "UpdatedAt")
                        .HasDatabaseName("ix_recipe_import_drafts_owner_user_id_updated_at");

                    b.ToTable("recipe_import_drafts", "imports");
                });
#pragma warning restore 612, 618
        }
    }
}
