// <auto-generated />
using System;
using MenuMate.Modules.MenuPlanning.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuMate.Modules.MenuPlanning.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MenuPlanningDbContext))]
    [Migration("20260608181221_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("menu_planning")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MealSlotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meal_slots");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_meal_slots_owner_user_id");

                    b.HasIndex("OwnerUserId", "SortOrder")
                        .HasDatabaseName("ix_meal_slots_owner_user_id_sort_order");

                    b.ToTable("meal_slots", "menu_planning");
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuCalendarItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("MealSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid?>("RecipeRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_revision_id");

                    b.Property<string>("RecipeTitle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("recipe_title");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_menu_calendar_items");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_menu_calendar_items_recipe_id");

                    b.HasIndex("RecipeRevisionId")
                        .HasDatabaseName("ix_menu_calendar_items_recipe_revision_id");

                    b.HasIndex("OwnerUserId", "Date")
                        .HasDatabaseName("ix_menu_calendar_items_owner_user_id_date");

                    b.HasIndex("OwnerUserId", "Date", "MealSlotId", "Position")
                        .HasDatabaseName("ix_menu_calendar_items_owner_user_id_date_meal_slot_id_position");

                    b.ToTable("menu_calendar_items", "menu_planning");
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Source.RecipeAccessSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", "recipes", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Source.RecipeRevisionAccessSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_revisions");

                    b.ToTable("recipe_revisions", "recipes", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
