// <auto-generated />
using System;
using MenuMate.Modules.MenuPlanning.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuMate.Modules.MenuPlanning.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MenuPlanningDbContext))]
    [Migration("20260531074445_InitialMenuPlanning")]
    partial class InitialMenuPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("menu_planning")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuPlanItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meal_type");

                    b.Property<Guid>("MenuPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_plan_id");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("RecipeTitle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("recipe_title");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_menu_plan_items");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_menu_plan_items_recipe_id");

                    b.HasIndex("MenuPlanId", "Date", "MealType")
                        .HasDatabaseName("ix_menu_plan_items_menu_plan_id_date_meal_type");

                    b.ToTable("menu_plan_items", "menu_planning");
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_menu_plans");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_menu_plans_end_date");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_menu_plans_owner_user_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_menu_plans_start_date");

                    b.ToTable("menu_plans", "menu_planning");
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuPlanItemRecord", b =>
                {
                    b.HasOne("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuPlanRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("MenuPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_plan_items_menu_plans_menu_plan_id");
                });

            modelBuilder.Entity("MenuMate.Modules.MenuPlanning.Infrastructure.Database.Entities.MenuPlanRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
